GENAI_KEY="pak-qBEXV1VQrIY3M-6tWfPtJewazq6aorItGrH4Uq2urWg"
GENAI_API="https://bam-api.res.ibm.com/v1/"

API_KEY="R9wxFDNqnfZ5TBXhmook4rPICqlrGKx_Q5Til2Y3NAfy"
PROJECT_ID="5dd9eb27-14f4-4573-b0bf-ad581fb8ec89"