GENAI_KEY="pak-qBEXV1VQrIY3M-6tWfPtJewazq6aorItGrH4Uq2urWg"
GENAI_API="https://bam-api.res.ibm.com/v1/"

API_KEY="UdbyUSRd6424vys5TlllcXpBRIncXyCqCFOBPGKdrH4C"
PROJECT_ID="832f255f-2d9f-4c82-92b4-25a54392650f"