GENAI_KEY="pak-qBEXV1VQrIY3M-6tWfPtJewazq6aorItGrH4Uq2urWg"
GENAI_API="https://bam-api.res.ibm.com/v1/"

API_KEY="6YuNMb3asYyCtfduVoQRsH2fPDB33ZNdhAQh7Y87rHgl"
PROJECT_ID="f86be7bf-6c82-492b-88cc-0297c1afc730"